### ISSUE TITLE
ERROR IN SUPPORT TICKET

### ISSUE THREAD

**Issue by SHASHANK2341** [NotSaksh/Shop-Managerx#8]
C:\Users\n5463\OneDrive\Desktop\CODING\Shop-Managerx-main\Shop-Managerx-main\modules\tickets\OrderSystem.js:498
            if(menuIndex.type){
                         ^

TypeError: Cannot read properties of undefined (reading 'type')
    at Client.<anonymous> (C:\Users\n5463\OneDrive\Desktop\CODING\Shop-Managerx-main\Shop-Managerx-main\modules\tickets\OrderSystem.js:498:26)
    at Client.emit (node:events:532:35)
    at InteractionCreateAction.handle (C:\Users\n5463\OneDrive\Desktop\CODING\Shop-Managerx-main\Shop-Managerx-main\node_modules\discord.js\src\client\actions\InteractionCreate.js:83:12)
    at Object.module.exports [as INTERACTION_CREATE] (C:\Users\n5463\OneDrive\Desktop\CODING\Shop-Managerx-main\Shop-Managerx-main\node_modules\discord.js\src\client\websocket\handlers\INTERACTION_CREATE.js:4:36)
    at WebSocketManager.handlePacket (C:\Users\n5463\OneDrive\Desktop\CODING\Shop-Managerx-main\Shop-Managerx-main\node_modules\discord.js\src\client\websocket\WebSocketManager.js:346:31)
    at WebSocketShard.onPacket (C:\Users\n5463\OneDrive\Desktop\CODING\Shop-Managerx-main\Shop-Managerx-main\node_modules\discord.js\src\client\websocket\WebSocketShard.js:478:22)
    at WebSocketShard.onMessage (C:\Users\n5463\OneDrive\Desktop\CODING\Shop-Managerx-main\Shop-Managerx-main\node_modules\discord.js\src\client\websocket\WebSocketShard.js:317:10)
    at WebSocket.onMessage (C:\Users\n5463\OneDrive\Desktop\CODING\Shop-Managerx-main\Shop-Managerx-main\node_modules\ws\lib\event-target.js:199:18)
    at WebSocket.emit (node:events:520:28)
    at Receiver.receiverOnMessage (C:\Users\n5463\OneDrive\Desktop\CODING\Shop-Managerx-main\Shop-Managerx-main\node_modules\ws\lib\websocket.js:1169:20)

Node.js v17.4.0

THIS COMES

**Comment by HyperQR** [comment]
use vps
